#!/bin/sh

./gcolor.py test_1 size=3 k=0 >> gcolor.log 
./gcolor.py test_1 size=3 k=1 >> gcolor.log 
./gcolor.py test_1 size=3 k=2 >> gcolor.log 
./gcolor.py test_1 size=3 k=3 >> gcolor.log 
./gcolor.py test_1 size=3 k=4 >> gcolor.log 
./gcolor.py test_1 size=3 k=5 >> gcolor.log 
./gcolor.py test_1 size=3 k=6 >> gcolor.log 
./gcolor.py test_1 size=3 k=7 >> gcolor.log 
./gcolor.py test_1 size=3 k=8 >> gcolor.log 
./gcolor.py test_1 size=3 k=9 >> gcolor.log 
./gcolor.py test_1 size=3 k=10 >> gcolor.log 
./gcolor.py test_1 size=3 k=11 >> gcolor.log 
./gcolor.py test_1 size=3 k=12 >> gcolor.log 
./gcolor.py test_1 size=3 k=13 >> gcolor.log 
./gcolor.py test_1 size=3 k=14 >> gcolor.log 
./gcolor.py test_1 size=3 k=15 >> gcolor.log 
./gcolor.py test_1 size=3 k=16 >> gcolor.log 
./gcolor.py test_1 size=3 k=17 >> gcolor.log 
./gcolor.py test_1 size=3 k=18 >> gcolor.log 
./gcolor.py test_1 size=3 k=19 >> gcolor.log 
./gcolor.py test_1 size=3 k=20 >> gcolor.log 
./gcolor.py test_1 size=3 k=21 >> gcolor.log 
./gcolor.py test_1 size=3 k=22 >> gcolor.log 
./gcolor.py test_1 size=3 k=23 >> gcolor.log 
./gcolor.py test_1 size=3 k=24 >> gcolor.log 
./gcolor.py test_1 size=3 k=25 >> gcolor.log 
./gcolor.py test_1 size=3 k=26 >> gcolor.log 
./gcolor.py test_1 size=3 k=27 >> gcolor.log 
./gcolor.py test_1 size=3 k=28 >> gcolor.log 
./gcolor.py test_1 size=3 k=29 >> gcolor.log 
./gcolor.py test_1 size=3 k=30 >> gcolor.log 
./gcolor.py test_1 size=3 k=31 >> gcolor.log 
./gcolor.py test_1 size=3 k=32 >> gcolor.log 
./gcolor.py test_1 size=3 k=33 >> gcolor.log 
./gcolor.py test_1 size=3 k=34 >> gcolor.log 
./gcolor.py test_1 size=3 k=35 >> gcolor.log 
./gcolor.py test_1 size=3 k=36 >> gcolor.log 
./gcolor.py test_1 size=3 k=37 >> gcolor.log 
./gcolor.py test_1 size=3 k=38 >> gcolor.log 
./gcolor.py test_1 size=3 k=39 >> gcolor.log 

